- name: Load k3s config
  delegate_to: localhost
  azure_rm_aks_info:
    name: "{{ azure_resource_group }}"
    resource_group: "{{ azure_resource_group }}"
    show_kubeconfig: admin
  register: k8s_config_raw

- name: Create admin config folder
  delegate_to: localhost
  file:
    path: "{{ k8s_admin_config_path | dirname }}"
    state: directory
    mode: 0700

- name: Create admin config
  delegate_to: localhost
  copy:
    dest: "{{ k8s_admin_config_path }}"
    content: "{{ k8s_config_raw.aks[0].kube_config }}"
    mode: 0600

- name: Get node details
  delegate_to: localhost
  k8s_info:
    kubeconfig: "{{ k8s_admin_config_path }}"
    kind: Node
  register: this
  failed_when: "'linux' != this.resources[0].status.nodeInfo.operatingSystem"