---
argument_specs:
  main:
    options:
      k8s_admin_config_path:
        type: str
        required: true
      traefik_chart_version:
        type: str
        required: true
      ip_range:
        type: list
        elements: str
        required: true
      