apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ k8s_namespace }}"
  namespace: "{{ k8s_namespace }}"
subjects:
- kind: ServiceAccount
  name: "{{ k8s_namespace }}"
  namespace: "{{ k8s_namespace }}"
roleRef:
  kind: Role
  name: "{{ k8s_namespace }}"
  apiGroup: rbac.authorization.k8s.io