apiVersion: v1
kind: Secret
metadata:
  name: "{{ k8s_namespace }}-token"
  namespace: "{{ k8s_namespace }}"
  annotations:
    kubernetes.io/service-account.name: "{{ k8s_namespace }}"
type: kubernetes.io/service-account-token