- name: Create Azure Kubernetes Service
  hosts: localhost
  connection: local
  vars:
    resource_group: cloud-roles
    location: centralus
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"